Revert "Neo: use parallel runtime for all queries"
This reverts commit 9aa5321f44cd66c382f8281bec2a5528bdd1f989.

> neo4j.exceptions.ClientError: {code: Neo.ClientError.Statement.RuntimeUnsupportedError} {message: Parallel does not yet support `TriadicSelection`, use another runtime.}